### PR TITLE
Fix path for bfx-api-node-models

### LINKED ISSUE #8: Cannot find module 'bfx-api-node-models' in v1.0.4
#### Issue type
- [ X ] bug

#### Brief description

Use package "bfx-api-node-models" in lib/res_notification_info.js which is located in devDependencies.

It will be broken when you use it in production (will not install devDependencies XD).

### PR DESCRIPTION
**Pull request by ezewer**
Change path for bfx-api-node-models from github to npm

### Description:
Change path for bfx-api-node-models from github to npm

### Breaking changes:
- no

### New features:
- no

### Fixes:
fixes #8

### PR status:
- [ 1.0.5 ] Version bumped
- [ no ] Change-log updated
- [ no ] Tests added or updated

### CODE REVIEW

**Comment by JacobPlaster** [comment]
In regards to https://github.com/bitfinexcom/bfx-api-node-util/issues/8 could we not just move the dependency out of `devDeps`? Why is npm better than github semVer?

**Comment by JacobPlaster** [comment]
FYI - asked the same question (^) in the original issue thread

**Comment by ezewer** [comment]
@JacobPlaster `In regards to #8 could we not just move the dependency out of devDeps? ` yes this is done, added to `deps` as its being used on the actual code.
Regarding npm just as to keep consistency with the other dependencies.

**Comment by JacobPlaster** [comment]
Looks good!

**Pull request merged**
